# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CountryCapital' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CountryCapital

  def testing_pods
      pod 'Quick', '5.0.1'
      pod 'Nimble', '10.0.0'
      pod 'ViewInspector', '0.9.9'
  end

  target 'CountryCapitalTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

  target 'CountryCapitalUITests' do
    # Pods for testing
    testing_pods
  end

end
